import {
  Character,
  ColorTheme,
  FontAsset,
  Page,
  Project,
  StickerAsset,
  TextureAsset,
  VoiceOption,
  WorkspaceMeta,
  WorkspaceKey,
  FamilyMember,
} from "@/types";
import { uid } from "@/utils/id";

export const WORKSPACES: WorkspaceMeta[] = [
  {
    key: "storyboard",
    name: "故事板",
    description: "规划页码、场景和角色关系",
    icon: "BookOpen",
    color: "coral",
    gradient: "from-coral-400 via-peach-400 to-lemon-400",
    path: "/workspace/storyboard",
    emoji: "📖",
  },
  {
    key: "painting",
    name: "绘画台",
    description: "画笔、贴纸、纹理、图层",
    icon: "Palette",
    color: "sky",
    gradient: "from-sky-400 via-mint-400 to-lemon-400",
    path: "/workspace/painting",
    emoji: "🎨",
  },
  {
    key: "characters",
    name: "角色库",
    description: "表情、服装和姿势管理",
    icon: "Users",
    color: "lemon",
    gradient: "from-lemon-400 via-peach-400 to-coral-400",
    path: "/workspace/characters",
    emoji: "🧸",
  },
  {
    key: "text",
    name: "文字台",
    description: "气泡对白、旁白和朗读预览",
    icon: "MessageCircle",
    color: "mint",
    gradient: "from-mint-400 via-sky-400 to-lilac-400",
    path: "/workspace/text",
    emoji: "💬",
  },
  {
    key: "color",
    name: "配色台",
    description: "主题色推荐与画面统一检查",
    icon: "Droplets",
    color: "lilac",
    gradient: "from-lilac-400 via-sky-400 to-mint-400",
    path: "/workspace/color",
    emoji: "🌈",
  },
  {
    key: "composite",
    name: "合成台",
    description: "封面、跨页和缩略图生成",
    icon: "LayoutGrid",
    color: "peach",
    gradient: "from-peach-400 via-coral-400 to-lemon-400",
    path: "/workspace/composite",
    emoji: "📚",
  },
  {
    key: "share",
    name: "分享台",
    description: "导出PDF、图片集和朗读视频",
    icon: "Share2",
    color: "coral",
    gradient: "from-coral-400 via-lilac-400 to-sky-400",
    path: "/workspace/share",
    emoji: "🎁",
  },
];

export const DEFAULT_PROJECT: Project = {
  id: uid(),
  title: "小兔子的森林冒险",
  author: "亲子创作组",
  coverColor: "#FFE66D",
  totalPages: 6,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const COLOR_THEMES: ColorTheme[] = [
  {
    id: "fairy-tale",
    name: "童话王国",
    description: "温暖梦幻的童话风格",
    primary: "#FFB6C1",
    secondary: "#FFE4E1",
    accent: "#DDA0DD",
    palette: ["#FFB6C1", "#FFEFD5", "#E6E6FA", "#DDA0DD", "#87CEEB", "#FFFACD"],
    background: "#FFF8E7",
    mood: "梦幻",
  },
  {
    id: "forest",
    name: "森林系",
    description: "清新自然的森林气息",
    primary: "#7ED47E",
    secondary: "#A8D8A8",
    accent: "#8B7355",
    palette: ["#7ED47E", "#A8E6A8", "#8B7355", "#D2B48C", "#F5DEB3", "#C1E1C1"],
    background: "#F0FFF0",
    mood: "清新",
  },
  {
    id: "dreamy-purple",
    name: "梦幻紫",
    description: "神秘浪漫的紫色梦境",
    primary: "#A882D8",
    secondary: "#D8BFD8",
    accent: "#FFD700",
    palette: ["#A882D8", "#C8A2E0", "#E6E6FA", "#FFD700", "#FFB6C1", "#B0C4DE"],
    background: "#FAF5FF",
    mood: "浪漫",
  },
  {
    id: "ocean-blue",
    name: "海洋蓝",
    description: "清爽宁静的海洋世界",
    primary: "#4ECDC4",
    secondary: "#6FE0D8",
    accent: "#FFE66D",
    palette: ["#4ECDC4", "#6FE0D8", "#87CEEB", "#E0FFFF", "#FFE66D", "#F0F8FF"],
    background: "#F0FFFF",
    mood: "清爽",
  },
  {
    id: "sunset",
    name: "夕阳橙",
    description: "温暖热烈的夕阳时光",
    primary: "#FF8A4C",
    secondary: "#FFA775",
    accent: "#FF6B6B",
    palette: ["#FF8A4C", "#FFA775", "#FFE66D", "#FF6B6B", "#FFB6C1", "#FFEFD5"],
    background: "#FFF5EB",
    mood: "温暖",
  },
  {
    id: "candy",
    name: "糖果乐园",
    description: "缤纷甜蜜的糖果色彩",
    primary: "#FF6B6B",
    secondary: "#FFB0B0",
    accent: "#4ECDC4",
    palette: ["#FF6B6B", "#FFE66D", "#7ED47E", "#4ECDC4", "#A882D8", "#FFA775"],
    background: "#FFFAF0",
    mood: "甜蜜",
  },
  {
    id: "night",
    name: "星空夜",
    description: "静谧神秘的星夜主题",
    primary: "#4A4E89",
    secondary: "#6A6FAE",
    accent: "#FFE66D",
    palette: ["#4A4E89", "#6A6FAE", "#989BC4", "#FFE66D", "#FFD700", "#E6E6FA"],
    background: "#1C1F3B",
    mood: "神秘",
  },
  {
    id: "spring",
    name: "春日樱",
    description: "粉嫩柔美的春日樱花",
    primary: "#FFB6C1",
    secondary: "#FFC0CB",
    accent: "#7ED47E",
    palette: ["#FFB6C1", "#FFC0CB", "#FFE4E1", "#7ED47E", "#FFFACD", "#F0FFF0"],
    background: "#FFF5F8",
    mood: "柔美",
  },
];

export const STICKER_ASSETS: StickerAsset[] = [
  { id: "s1", name: "小兔子", category: "动物", emoji: "🐰", tags: ["兔子", "可爱"] },
  { id: "s2", name: "小狐狸", category: "动物", emoji: "🦊", tags: ["狐狸"] },
  { id: "s3", name: "小熊", category: "动物", emoji: "🐻", tags: ["熊"] },
  { id: "s4", name: "小猫", category: "动物", emoji: "🐱", tags: ["猫"] },
  { id: "s5", name: "小狗", category: "动物", emoji: "🐶", tags: ["狗"] },
  { id: "s6", name: "小鸟", category: "动物", emoji: "🐦", tags: ["鸟"] },
  { id: "s7", name: "蝴蝶", category: "动物", emoji: "🦋", tags: ["蝴蝶", "昆虫"] },
  { id: "s8", name: "小松鼠", category: "动物", emoji: "🐿️", tags: ["松鼠"] },
  { id: "s9", name: "刺猬", category: "动物", emoji: "🦔", tags: ["刺猬"] },
  { id: "s10", name: "小鹿", category: "动物", emoji: "🦌", tags: ["鹿"] },
  { id: "s11", name: "樱花", category: "植物", emoji: "🌸", tags: ["花", "樱花"] },
  { id: "s12", name: "向日葵", category: "植物", emoji: "🌻", tags: ["花"] },
  { id: "s13", name: "四叶草", category: "植物", emoji: "🍀", tags: ["草", "幸运"] },
  { id: "s14", name: "大树", category: "植物", emoji: "🌳", tags: ["树"] },
  { id: "s15", name: "松树", category: "植物", emoji: "🌲", tags: ["树"] },
  { id: "s16", name: "蘑菇", category: "植物", emoji: "🍄", tags: ["蘑菇"] },
  { id: "s17", name: "仙人掌", category: "植物", emoji: "🌵", tags: ["仙人掌"] },
  { id: "s18", name: "郁金香", category: "植物", emoji: "🌷", tags: ["花"] },
  { id: "s19", name: "太阳", category: "天气", emoji: "☀️", tags: ["太阳"] },
  { id: "s20", name: "月亮", category: "天气", emoji: "🌙", tags: ["月亮"] },
  { id: "s21", name: "星星", category: "天气", emoji: "⭐", tags: ["星星"] },
  { id: "s22", name: "云朵", category: "天气", emoji: "☁️", tags: ["云"] },
  { id: "s23", name: "彩虹", category: "天气", emoji: "🌈", tags: ["彩虹"] },
  { id: "s24", name: "雪花", category: "天气", emoji: "❄️", tags: ["雪"] },
  { id: "s25", name: "闪电", category: "天气", emoji: "⚡", tags: ["闪电"] },
  { id: "s26", name: "爱心", category: "装饰", emoji: "❤️", tags: ["爱"] },
  { id: "s27", name: "礼物", category: "装饰", emoji: "🎁", tags: ["礼物"] },
  { id: "s28", name: "气球", category: "装饰", emoji: "🎈", tags: ["气球"] },
  { id: "s29", name: "皇冠", category: "装饰", emoji: "👑", tags: ["皇冠"] },
  { id: "s30", name: "小房子", category: "装饰", emoji: "🏠", tags: ["房子"] },
  { id: "s31", name: "城堡", category: "装饰", emoji: "🏰", tags: ["城堡"] },
  { id: "s32", name: "彩虹糖", category: "食物", emoji: "🍬", tags: ["糖"] },
  { id: "s33", name: "蛋糕", category: "食物", emoji: "🎂", tags: ["蛋糕"] },
  { id: "s34", name: "苹果", category: "食物", emoji: "🍎", tags: ["水果"] },
  { id: "s35", name: "胡萝卜", category: "食物", emoji: "🥕", tags: ["蔬菜"] },
  { id: "s36", name: "蜂蜜罐", category: "食物", emoji: "🍯", tags: ["蜂蜜"] },
];

export const TEXTURE_ASSETS: TextureAsset[] = [
  { id: "t1", name: "羊皮纸", category: "纸张", cssClass: "canvas-bg" },
  { id: "t2", name: "素描纸", category: "纸张", cssClass: "canvas-bg" },
  { id: "t3", name: "水彩纸", category: "纸张", cssClass: "canvas-bg" },
  { id: "t4", name: "牛皮纸", category: "纸张", cssClass: "canvas-bg" },
  { id: "t5", name: "彩虹渐变", category: "渐变", cssClass: "bg-rainbow-soft" },
  { id: "t6", name: "天空蓝", category: "纯色", cssClass: "bg-sky-400/20" },
  { id: "t7", name: "柠檬黄", category: "纯色", cssClass: "bg-lemon-400/30" },
  { id: "t8", name: "薄荷绿", category: "纯色", cssClass: "bg-mint-400/20" },
];

export const FONT_ASSETS: FontAsset[] = [
  { id: "f1", name: "快乐体", family: "'ZCOOL KuaiLe', cursive", category: "可爱体", preview: "彩虹绘本工坊 123" },
  { id: "f2", name: "马善政", family: "'Ma Shan Zheng', cursive", category: "手写体", preview: "彩虹绘本工坊 123" },
  { id: "f3", name: "思源黑体", family: "'Noto Sans SC', sans-serif", category: "标准体", preview: "彩虹绘本工坊 123" },
  { id: "f4", name: "圆体字", family: "'Noto Sans SC', sans-serif", category: "圆润体", preview: "彩虹绘本工坊 123" },
  { id: "f5", name: "美术字", family: "'ZCOOL KuaiLe', cursive", category: "卡通体", preview: "彩虹绘本工坊 123" },
  { id: "f6", name: "手写体", family: "'Ma Shan Zheng', cursive", category: "手写体", preview: "彩虹绘本工坊 123" },
];

export const VOICE_OPTIONS: VoiceOption[] = [
  { id: "v1", name: "小朋友", type: "child", pitch: 1.6, rate: 1.0, previewText: "大家好，我是小兔子！" },
  { id: "v2", name: "温柔妈妈", type: "mom", pitch: 1.2, rate: 0.9, previewText: "从前有一只可爱的小兔子..." },
  { id: "v3", name: "幽默爸爸", type: "dad", pitch: 0.8, rate: 1.0, previewText: "哈哈，这真是太棒啦！" },
  { id: "v4", name: "慈祥奶奶", type: "grandma", pitch: 1.0, rate: 0.8, previewText: "宝贝们，听奶奶讲故事..." },
  { id: "v5", name: "故事爷爷", type: "grandpa", pitch: 0.7, rate: 0.85, previewText: "很久很久以前...嗯..." },
];

export const FAMILY_MEMBERS: FamilyMember[] = [
  { id: "m1", name: "爸爸", avatar: "👨", role: "家长", canComment: true, canEdit: true },
  { id: "m2", name: "妈妈", avatar: "👩", role: "家长", canComment: true, canEdit: true },
  { id: "m3", name: "小明", avatar: "👦", role: "创作者", canComment: true, canEdit: true },
  { id: "m4", name: "小红", avatar: "👧", role: "创作者", canComment: true, canEdit: true },
  { id: "m5", name: "奶奶", avatar: "👵", role: "读者", canComment: true, canEdit: false },
];

export const MOCK_CHARACTERS: Character[] = [
  {
    id: "c1",
    projectId: "p1",
    name: "小兔可可",
    color: "#FFB6C1",
    avatar: "🐰",
    description: "勇敢善良的小兔子，喜欢冒险",
    expressions: [
      { id: "e1", name: "开心", emoji: "😄" },
      { id: "e2", name: "惊讶", emoji: "😲" },
      { id: "e3", name: "伤心", emoji: "😢" },
      { id: "e4", name: "生气", emoji: "😠" },
      { id: "e5", name: "思考", emoji: "🤔" },
      { id: "e6", name: "爱心", emoji: "🥰" },
    ],
    costumes: [
      { id: "co1", name: "日常装", color: "#FFB6C1", icon: "👕" },
      { id: "co2", name: "冒险装", color: "#87CEEB", icon: "🎽" },
      { id: "co3", name: "礼服", color: "#DDA0DD", icon: "👗" },
      { id: "co4", name: "雨衣", color: "#FFE66D", icon: "🧥" },
    ],
    poses: [
      { id: "p1", name: "站立", icon: "🧍" },
      { id: "p2", name: "跑步", icon: "🏃" },
      { id: "p3", name: "跳跃", icon: "🤸" },
      { id: "p4", name: "挥手", icon: "🙋" },
      { id: "p5", name: "坐姿", icon: "🧘" },
    ],
  },
  {
    id: "c2",
    projectId: "p1",
    name: "狐狸小橘",
    color: "#FFA775",
    avatar: "🦊",
    description: "聪明机灵的好朋友",
    expressions: [
      { id: "e7", name: "狡黠", emoji: "😏" },
      { id: "e8", name: "大笑", emoji: "😂" },
      { id: "e9", name: "得意", emoji: "😎" },
      { id: "e10", name: "害羞", emoji: "😳" },
    ],
    costumes: [
      { id: "co5", name: "休闲装", color: "#FFA775", icon: "👕" },
      { id: "co6", name: "读书装", color: "#8B7355", icon: "🎓" },
    ],
    poses: [
      { id: "p6", name: "站立", icon: "🧍" },
      { id: "p7", name: "抱臂", icon: "🙆" },
      { id: "p8", name: "指方向", icon: "👉" },
    ],
  },
  {
    id: "c3",
    projectId: "p1",
    name: "熊大叔",
    color: "#D2B48C",
    avatar: "🐻",
    description: "温暖可靠的森林长者",
    expressions: [
      { id: "e11", name: "慈祥", emoji: "😊" },
      { id: "e12", name: "瞌睡", emoji: "😴" },
      { id: "e13", name: "大笑", emoji: "😆" },
    ],
    costumes: [
      { id: "co7", name: "背心", color: "#8B4513", icon: "🎽" },
      { id: "co8", name: "围裙", color: "#FFE4B5", icon: "👨‍🍳" },
    ],
    poses: [
      { id: "p9", name: "站立", icon: "🧍" },
      { id: "p10", name: "招手", icon: "👋" },
    ],
  },
];

export function createMockPages(projectId: string): Page[] {
  return [
    {
      id: uid(),
      projectId,
      pageNumber: 1,
      background: { type: "color", value: "#FFFACD", name: "淡黄色" },
      sceneDescription: "封面 - 小兔子站在森林入口",
      strokes: [],
      textBubbles: [
        {
          id: uid(),
          pageId: "",
          type: "narration",
          content: "小兔子的森林冒险",
          font: "'ZCOOL KuaiLe', cursive",
          fontSize: 48,
          color: "#5D4E37",
          x: 200,
          y: 120,
          width: 400,
          height: 80,
        },
      ],
      stickers: [
        { id: uid(), pageId: "", assetId: "s1", x: 300, y: 300, scale: 2, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s14", x: 100, y: 200, scale: 1.5, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s23", x: 450, y: 80, scale: 1.2, rotation: 0 },
      ],
      characterRelations: [],
    },
    {
      id: uid(),
      projectId,
      pageNumber: 2,
      background: { type: "color", value: "#E4F5E4", name: "薄荷绿" },
      sceneDescription: "第1页 - 小兔子决定去冒险",
      strokes: [],
      textBubbles: [
        {
          id: uid(),
          pageId: "",
          type: "speech",
          content: "今天天气真好！我要去森林探险！",
          font: "'ZCOOL KuaiLe', cursive",
          fontSize: 22,
          color: "#5D4E37",
          x: 100,
          y: 60,
          width: 300,
          height: 60,
          tailDirection: "bottom",
        },
      ],
      stickers: [
        { id: uid(), pageId: "", assetId: "s1", x: 200, y: 280, scale: 2, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s19", x: 500, y: 60, scale: 1.5, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s15", x: 520, y: 280, scale: 1.8, rotation: 0 },
      ],
      characterRelations: [],
    },
    {
      id: uid(),
      projectId,
      pageNumber: 3,
      background: { type: "color", value: "#FFF1E0", name: "桃色" },
      sceneDescription: "第2页 - 遇到小狐狸",
      strokes: [],
      textBubbles: [
        {
          id: uid(),
          pageId: "",
          type: "speech",
          content: "嘿！小兔子，你要去哪里？",
          font: "'ZCOOL KuaiLe', cursive",
          fontSize: 22,
          color: "#5D4E37",
          x: 350,
          y: 60,
          width: 260,
          height: 60,
          tailDirection: "bottom",
        },
        {
          id: uid(),
          pageId: "",
          type: "speech",
          content: "我要去森林深处探险！一起来吗？",
          font: "'ZCOOL KuaiLe', cursive",
          fontSize: 22,
          color: "#5D4E37",
          x: 50,
          y: 180,
          width: 280,
          height: 60,
          tailDirection: "right",
        },
      ],
      stickers: [
        { id: uid(), pageId: "", assetId: "s1", x: 100, y: 300, scale: 1.8, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s2", x: 440, y: 300, scale: 1.8, rotation: 0 },
      ],
      characterRelations: [],
    },
    {
      id: uid(),
      projectId,
      pageNumber: 4,
      background: { type: "color", value: "#E6E6FA", name: "淡紫色" },
      sceneDescription: "第3页 - 遇见熊大叔",
      strokes: [],
      textBubbles: [
        {
          id: uid(),
          pageId: "",
          type: "narration",
          content: "他们走啊走，遇到了正在吃蜂蜜的熊大叔...",
          font: "'Ma Shan Zheng', cursive",
          fontSize: 24,
          color: "#5D4E37",
          x: 120,
          y: 30,
          width: 440,
          height: 50,
        },
      ],
      stickers: [
        { id: uid(), pageId: "", assetId: "s1", x: 120, y: 320, scale: 1.5, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s2", x: 250, y: 340, scale: 1.5, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s3", x: 440, y: 260, scale: 2, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s36", x: 460, y: 380, scale: 1.2, rotation: 0 },
      ],
      characterRelations: [],
    },
    {
      id: uid(),
      projectId,
      pageNumber: 5,
      background: { type: "color", value: "#FFEFD1", name: "米黄色" },
      sceneDescription: "第4页 - 发现神秘宝藏",
      strokes: [],
      textBubbles: [
        {
          id: uid(),
          pageId: "",
          type: "shout",
          content: "哇！是宝箱！",
          font: "'ZCOOL KuaiLe', cursive",
          fontSize: 32,
          color: "#FF6B6B",
          x: 200,
          y: 50,
          width: 280,
          height: 60,
        },
      ],
      stickers: [
        { id: uid(), pageId: "", assetId: "s1", x: 120, y: 320, scale: 1.6, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s2", x: 280, y: 340, scale: 1.6, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s3", x: 480, y: 320, scale: 1.6, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s27", x: 320, y: 200, scale: 2, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s21", x: 300, y: 100, scale: 1, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s21", x: 380, y: 130, scale: 1.2, rotation: 0 },
      ],
      characterRelations: [],
    },
    {
      id: uid(),
      projectId,
      pageNumber: 6,
      background: { type: "color", value: "#E0FFFF", name: "青蓝色" },
      sceneDescription: "封底 - 大家开心地回家",
      strokes: [],
      textBubbles: [
        {
          id: uid(),
          pageId: "",
          type: "narration",
          content: "他们带着满满的收获，开心地回家了。",
          font: "'Ma Shan Zheng', cursive",
          fontSize: 26,
          color: "#5D4E37",
          x: 120,
          y: 80,
          width: 440,
          height: 60,
        },
        {
          id: uid(),
          pageId: "",
          type: "narration",
          content: "— 完 —",
          font: "'ZCOOL KuaiLe', cursive",
          fontSize: 36,
          color: "#A882D8",
          x: 260,
          y: 180,
          width: 160,
          height: 60,
        },
      ],
      stickers: [
        { id: uid(), pageId: "", assetId: "s1", x: 140, y: 300, scale: 1.6, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s2", x: 280, y: 320, scale: 1.6, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s3", x: 430, y: 300, scale: 1.6, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s26", x: 260, y: 260, scale: 1, rotation: 0 },
        { id: uid(), pageId: "", assetId: "s26", x: 350, y: 250, scale: 1.2, rotation: 0 },
      ],
      characterRelations: [],
    },
  ];
}

export function createSampleProjects(): Project[] {
  const now = new Date();
  return [
    {
      id: "p1",
      title: "小兔子的森林冒险",
      author: "小明 & 妈妈",
      coverColor: "#FFE66D",
      totalPages: 6,
      createdAt: new Date(now.getTime() - 86400000 * 3),
      updatedAt: new Date(now.getTime() - 3600000),
    },
    {
      id: "p2",
      title: "海底小纵队",
      author: "小红 & 爸爸",
      coverColor: "#4ECDC4",
      totalPages: 8,
      createdAt: new Date(now.getTime() - 86400000 * 7),
      updatedAt: new Date(now.getTime() - 86400000),
    },
    {
      id: "p3",
      title: "太空梦游记",
      author: "全家总动员",
      coverColor: "#A882D8",
      totalPages: 10,
      createdAt: new Date(now.getTime() - 86400000 * 14),
      updatedAt: new Date(now.getTime() - 86400000 * 5),
    },
  ];
}

export function getWorkspaceMeta(key: WorkspaceKey): WorkspaceMeta | undefined {
  return WORKSPACES.find((w) => w.key === key);
}
